"""empty message

Revision ID: 0aebbe6efac8
Revises: fb0ad092d9ca
Create Date: 2022-05-17 11:21:27.339792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0aebbe6efac8'
down_revision = 'fb0ad092d9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
