"""empty message

Revision ID: 4b8386e49b9f
Revises: fbe740899d45
Create Date: 2022-06-02 11:11:30.496041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b8386e49b9f'
down_revision = 'fbe740899d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'headline',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('news', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('news', 'headline',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
