"""empty message

Revision ID: 4c891bf56b3f
Revises: 52432178a195
Create Date: 2022-05-19 13:49:30.930647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c891bf56b3f'
down_revision = '52432178a195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False, foriegn_key=True),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('polling',
    sa.Column('polling_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('polling_id')
    )
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('hashtag', sa.String(length=80), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=False),
    sa.Column('edited_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('polling')
    op.drop_table('images')
    op.drop_table('birthday')
    # ### end Alembic commands ###
