"""empty message

Revision ID: 523af708ef9e
Revises: 97f17f40c122
Create Date: 2022-06-01 13:47:01.657165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '523af708ef9e'
down_revision = '97f17f40c122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_path', sa.String(length=80), nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('images', 'image_path')
    # ### end Alembic commands ###
