"""empty message

Revision ID: 52432178a195
Revises: 0aebbe6efac8
Create Date: 2022-05-19 13:48:06.053447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52432178a195'
down_revision = '0aebbe6efac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('ADMIN', 'USER'),
               type_=sa.Enum('USER', 'ADMIN', name='rolesenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='rolesenum'),
               type_=mysql.ENUM('ADMIN', 'USER'),
               existing_nullable=True)
    # ### end Alembic commands ###
