"""empty message

Revision ID: 97f17f40c122
Revises: 52bf7ff5a9a5
Create Date: 2022-05-27 13:30:14.114382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97f17f40c122'
down_revision = '52bf7ff5a9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'edited_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'edited_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
