"""empty message

Revision ID: eee0244459f3
Revises: 6b257d754a4d
Create Date: 2022-05-19 14:07:51.707681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee0244459f3'
down_revision = '6b257d754a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'images', 'news', ['news_id'], ['news_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    # ### end Alembic commands ###
