"""empty message

Revision ID: fbe740899d45
Revises: 523af708ef9e
Create Date: 2022-06-01 20:40:46.722543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbe740899d45'
down_revision = '523af708ef9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'description',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
